[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./entrypoint.sh"
healthcheckPath = ""
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[[services]]
name = "gateway"
